name: Agent Studio
description: |
  Cloudera AI Agent Studio is a workspace for developing and deploying AI agentic workflows.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-07-22"

environment_variables:
  AGENT_STUDIO_NUM_WORKFLOW_RUNNERS:
    default: "5"
    required: true
    description: >-
      Number of workflow runners to spawn for testing workflows within Agent Studio. If multiple concurrent 
      users of Agent Studio are expected, you can increase this number accordingly.

runtimes:
  - editor: PBJ Workbench
    kernel: Agent Studio
    edition: Agent Studio

tasks:
  - type: start_application
    name: "Agent Studio"
    short_summary: Start Cloudera AI Agent Studio
    subdomain: cai-agent-studio
    script: run-app.py
    long_summary: This application launches an agent studio backend and frontend application.
    bypass_authentication: true
    cpu: 4
    memory: 16
    is_embedded: true
    environment_variables:
      TASK_TYPE: START_APPLICATION